#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  branches:
    '{master,dev,feature/SM0G-107-implement-update-coverage-testing-for-refactored-code}':
      - step:
          name: Test
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - pip install pytest
            - pip install coverage
            - coverage run --source=. --omit=definitions.py,test.py,run_perf.py --branch -m pytest -v --junitxml=test-reports/report.xml
            - coverage report -m
          